#
# Makefile
# anatharaman, 2017-07-26 14:31
#

all:
	clang -o C37_config1 C37_config1.c `pkg-config --cflags --libs libhammer`
	clang -o C37_data1 C37_data1.c `pkg-config --cflags --libs libhammer`
	clang -o C37_data3 C37_data3.c `pkg-config --cflags --libs libhammer`
	clang -o C37_datat C37_datat.c `pkg-config --cflags --libs libhammer`

# vim:ft=make
#

